[package]
name = "yabusame"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["serde-well-known"] }
tz-rs = "0.5.3"
