[package]
name = "yabusite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
argh = "0.1.7"
axum = "0.4.6"
tokio = { version = "1.17.0", features = ["full"] }
