[package]
name = "yabusite"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
argh = "0.1.7"
axum = "0.4.6"
tokio = { version = "1.17.0", features = ["full"] }
